# Generated by Django 2.1.7 on 2019-03-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20190329_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
