# Generated by Django 2.1.7 on 2019-03-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20190329_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='content',
            new_name='article',
        ),
    ]
