# Generated by Django 2.1.7 on 2019-03-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20190329_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='article',
        ),
    ]
