# Generated by Django 2.1.7 on 2019-03-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_remove_category_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.TextField(blank=True, null=True),
        ),
    ]
