# Generated by Django 2.1.7 on 2019-04-06 17:41

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20190406_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markdown',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
